RENDER=prman
FILE=egg
SLCOMPILER=oslc
VIEWER=sho
SLEXT=oso

SHADERNAME_COLOUR= eggSurface

SHADERNAME_COLOUR2 = eggSurface2

SHADERNAME_WOOD = wood

SHADERNAME_DISPLACEMENT= eggDisplacement


all : ${FILE}.tiff
	${VIEWER} ${FILE}.tiff

${SHADERNAME_COLOUR}.${SLEXT} : ${SHADERNAME_COLOUR}.osl
	${SLCOMPILER} ${SHADERNAME_COLOUR}.osl	

${SHADERNAME_COLOUR2}.${SLEXT} : ${SHADERNAME_COLOUR2}.osl
	${SLCOMPILER} ${SHADERNAME_COLOUR2}.osl	

${SHADERNAME_WOOD}.${SLEXT} : ${SHADERNAME_WOOD}.osl
	${SLCOMPILER} ${SHADERNAME_WOOD}.osl	

${SHADERNAME_DISPLACEMENT}.${SLEXT} : ${SHADERNAME_DISPLACEMENT}.osl
	${SLCOMPILER} ${SHADERNAME_DISPLACEMENT}.osl	

${FILE}.tiff : ${SHADERNAME_COLOUR}.${SLEXT} ${SHADERNAME_COLOUR2}.${SLEXT}	${SHADERNAME_WOOD}.${SLEXT} ${SHADERNAME_DISPLACEMENT}.${SLEXT} ${FILE}.rib
	cat ${FILE}.rib | sed s/XXXX/${SHADERNAME}/g | ${RENDER}

clean :
	rm -f *.tiff *.${SLEXT}
